enum SConst {

	STATUS_MESSAGE = "statusmessage",
	EXTRA_CONTENT = "extracontent",

	MILI_SEC = 1000,
	MILI_MIN = 60000,
	MILI_HOUR = 3600000,
	MILI_DAY = 86400000,
	MILI_WEEK = 604800000,
	MILI_MONTH = 2592000000,
	MILI_YEAR = 31536000000,

	BYTE_SIZE = 1,
	KILOBYTE_SIZE = 1000,
	MEGBYTE_SIZE = 1000000,

	FETCH_LIST_LIMIT = 30,

	X_ACCESS_TOKEN = "x-access-token",
	X_REFRESH_TOKEN = "x-refresh-token",

	HTTP_METHOD_GET = "get",
	HTTP_METHOD_POST = "post",
	HTTP_METHOD_DELETE = "delete",
	HTTP_METHOD_PUT = "put",
	HTTP_METHOD_PATCH = "patch",

	VAL_TELEPHONE_MAX_SIZE = 13,
	VAL_TELEPHONE_MIN_SIZE = 9,
	VAL_NAME_MAX_SIZE = 60,
	VAL_NAME_MIN_SIZE = 3,
	VAL_LOGIN_MAX_SIZE = 16,
	VAL_LOGIN_MIN_SIZE = 5,
	VAL_PASSWORD_MAX_SIZE = 30,
	VAL_PASSWORD_MIN_SIZE = 8,

	TEST_ROLE_NORMAL_USER = "NORMAL",
	TEST_ROLE_NEW_USER = "NEW",
	TEST_ROLE_ADMIN_USER = "ADMIN",

	KEY_EMPTY_TOKEN = "-"
}

export default SConst;
